export const ActionTypes = {
    GET_WU_NUMBER_REQUEST: 'POST_WU_NUMBER',
    GET_WU_NUMBER_SUCCESS: 'POST_WU_NUMBER_SUCCESS',
    GET_WU_NUMBER_FAILED: 'POST_WU_NUMBER_FAILED',
    GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_FAILED: 'GET_COUNTRIES_FAILED',
    GET_STATES_REQUEST: 'GET_STATES_REQUEST',
    GET_STATES_SUCCESS: 'GET_STATES_SUCCESS',
    GET_STATES_FAILED: 'GET_STATES_FAILED',

    POST_TRANSACTION_DETAILS_REQUEST: 'POST_TRANSACTION_DETAILS_REQUST',
    POST_TRANSACTION_DETAILS: 'POST_TRANSACTION_DETAILS',
    POST_TRANSACTION_DETAILS_FAILED: 'POST_TRANSACTION_DETAILS_FAILED',

    POST_DELIVERY_DATA_REQUEST: 'POST_DELIVERY_DATA_REQUEST',
    POST_DELIVERY_DATA: 'POST_DELIVERY_DATA',
    POST_DELIVERY_DATA_FAILED: 'POST_DELIVERY_DATA_FAILED'
}