export const ActionTypes = {
    GET_WU_NUMBER_REQUEST: 'POST_WU_NUMBER',
    GET_WU_NUMBER_SUCCESS: 'POST_WU_NUMBER_SUCCESS',
    GET_WU_NUMBER_FAILED: 'POST_WU_NUMBER_FAILED',
    GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_FAILED: 'GET_COUNTRIES_FAILED'
}