export const ActionTypes = {
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILED: 'GET_USER_FAILED',
    GET_INCOME_DETAILS_REQUEST: 'GET_INCOME_DETAILS_REQUEST',
    GET_INCOME_DETAILS_SUCCESS: 'GET_INCOME_DETAILS_SUCCESS',
    GET_INCOME_DETAILS_FAILED: 'GET_INCOME_DETAILS_FAILED',
    GET_STORE_REQUEST: 'GET_STORE_REQUEST',
    GET_STORE_SUCCESS: 'GET_STORE_SUCCESS',
    GET_STORE_FAILED: 'GET_STORE_FAILED',
}