export const ActionTypes = {
    GET_TRANSACTION_HISTORY_REQUEST: 'GET_TRANSACTION_HISTORY_REQUEST',
    GET_TRANSACTION_HISTORY_SUCCESS: 'GET_TRANSACTION_HISTORY_SUCCESS',
    GET_TRANSACTION_HISTORY_FAILED: 'GET_TRANSACTION_HISTORY_FAILED',
}