export const ActionTypes = {
    GET_ALL_ARTICLES_REQUEST: 'GET_ALL_ARTICLES_REQUEST',
    GET_ALL_ARTICLES: 'GET_ALL_ARTICLES',
    GET_ALL_ARTICLES_FAILED: 'GET_ALL_ARTICLES_FAILED',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED'
}