export const ActionTypes = {
    GET_ALL_ARTICLES_REQUEST: 'GET_ALL_ARTICLES_REQUEST',
    GET_ALL_ARTICLES: 'GET_ALL_ARTICLES',
    GET_ALL_ARTICLES_FAILED: 'GET_ALL_ARTICLES_FAILED',
    GET_WU_NUMBER_REQUEST: 'POST_WU_NUMBER',
    GET_WU_NUMBER_SUCCESS: 'POST_WU_NUMBER_SUCCESS',
    GET_WU_NUMBER_FAILED: 'POST_WU_NUMBER_FAILED',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED'
}